---
abstract: 'Specify function execution time limit'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-Sub-property-timeout
requires:
  Perinci: 0
  Perinci::Sub::Wrapper: 0.08
  Test::More: 0.96
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Perinci-Sub-property-timeout/
  repository: http://github.com/sharyanto/perl-Perinci-Sub-property-timeout
version: 0.01
